spring:
  application:
    name: Dguard
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
management:
  trace:
    http:
      enabled: true
  info:
    git:
      mode: full
  endpoint:
    httptrace:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "Dguard"

server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    com.example.tr: info
    org.springframework.web: debug

